### PR TITLE
Created a new page that displays a table of Git stats that is sortable and has tooltips.

### PR DESCRIPTION
**Pull request by zhouyaoji**
The PR also contains a Rakefile and two library files for calling the Git API and storing encoded/encrypted credentials.

### CODE REVIEW

**Comment by zhouyaoji** [comment]
@davglass Hi Dav, is it possible to get a review of the PR? Thanks!

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by davglass** [comment]
This looks like you did a lot of work to make this, thanks for that. However, this seems way too manual of a process to get this information. Our current page is already static, I'd like to fix that in the future (when I have time) and this would be a nice addition to that. But only if it was in real time and didn't require a build step to be automated and tracked.

**Comment by zhouyaoji** [comment]
@davglass Okay, so I guess we close this PR for now? I will see if I have time next quarter to work on making the table dynamically update the statistics.

**Comment by davglass** [comment]
Yeah, let's close this one for now. I'd love it if all of the pages were dynamic and we had a nicer layout/design too :)

**Pull request closed without merging**
